name: pytorch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39hd77b12b_7
  - ca-certificates=2023.12.12=haa95532_0
  - certifi=2023.11.17=py39haa95532_0
  - cffi=1.16.0=py39h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.7=py39h89fc84f_0
  - cuda-cccl=12.3.101=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.3.101=0
  - cuda-runtime=11.8.0=0
  - filelock=3.13.1=py39haa95532_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - gmpy2=2.1.2=py39h7f96b67_0
  - idna=3.4=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.2=py39haa95532_0
  - jpeg=9e=h2bbff1b_1
  - lerc=3.0=hd77b12b_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.4.101=0
  - libcurand-dev=10.3.4.101=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.8=py39h2bbff1b_0
  - mkl_random=1.2.4=py39h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py39haa95532_0
  - networkx=3.1=py39haa95532_0
  - numpy=1.26.2=py39h055cbcc_0
  - numpy-base=1.26.2=py39h65a83cf_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.12=h2bbff1b_0
  - pillow=10.0.1=py39h045eedc_0
  - pip=23.3.1=py39haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py39haa95532_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.18=h1aa4202_0
  - pytorch=2.1.1=py3.9_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py39h2bbff1b_0
  - requests=2.31.0=py39haa95532_0
  - setuptools=68.2.2=py39haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - sympy=1.12=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - typing_extensions=4.7.1=py39haa95532_0
  - urllib3=1.26.18=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.26.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - cachetools==4.2.4
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.2.0
      - cupy-cuda11x==12.3.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fastrlock==0.8.2
      - fonttools==4.47.2
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.0
      - huggingface-hub==0.20.2
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.10.0
      - loguru==0.7.2
      - markdown==3.5.2
      - matplotlib==3.8.2
      - multidict==6.0.4
      - oauthlib==3.2.2
      - packaging==23.2
      - pandas==2.1.4
      - protobuf==4.25.3
      - psutil==5.9.7
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch-lightning==2.1.3
      - pytz==2023.3.post1
      - regex==2023.12.25
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - sentry-sdk==1.40.5
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - spikingjelly==0.0.0.0.12
      - tensorboard==2.0.2
      - threadpoolctl==3.2.0
      - timm==0.9.12
      - tokenizers==0.15.0
      - torch-geometric==2.4.0
      - torchaudio==2.1.1
      - torchinfo==1.8.0
      - torchmetrics==1.2.1
      - torchvision==0.16.1
      - tqdm==4.66.1
      - transformers==4.36.2
      - tzdata==2023.3
      - wandb==0.16.3
      - werkzeug==3.0.1
      - win32-setctime==1.1.0
      - yacs==0.1.8
      - yarl==1.9.4
      - zipp==3.17.0
prefix: D:\APP\Work\Anaconda\envs\pytorch
